# Generated by Django 4.2.5 on 2023-09-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_alter_person_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
