# Generated by Django 4.2.5 on 2023-09-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=None),
        ),
    ]
